CLUSTER = '<%= @cluster %>'
DOMAIN = '<%= @domain %>'
ENV = '<%= @env %>'
SSH_KEY = '<%= @ssh_key %>'
PROJECT_NAME = '<%= @project_name %>'
SCL_NAME = '<%= @scl_name %>'
WEBPAY_DIR = '<%= @webpay_dir %>'
