#!/bin/bash
#
# chkconfig: 35 68 38
# description: Starts supervisor
#
# @author Jeremy Orem <oremj@mozilla.com>
# 

NAME="<%= @name %>"
PROG_NAME=$NAME
SUPERVISOR=/usr/bin/supervisorctl
<% if not @environ.empty? -%>
export <%= @environ %>
<% end -%>

# Source function library.
. /etc/rc.d/init.d/functions

start() {
    echo -n $"Starting $PROG_NAME: "

    $SUPERVISOR start $NAME
    RETVAL=$?
    echo_success
    return $RETVAL

}

restart() {
    echo -n $"Restarting $PROG_NAME: "

    $SUPERVISOR restart $NAME
    RETVAL=$?
    echo_success
    return $RETVAL

}

_graceful() {
    G_PID=$($SUPERVISOR pid $NAME)
    if [[ $G_PID -gt 0 ]]
    then
        echo -n $"Gracefully restarting $PROG_NAME: "
        /bin/kill -HUP $G_PID
        RETVAL=$?
        echo_success
        return $RETVAL
    else
        restart
        return $?
    fi
}

graceful() {
    <% if not @configtest_command.empty? -%>
    <%= @configtest_command %> && _graceful
    <% else -%>
    _graceful
    <% end -%>
    RETVAL=$?
    return $RETVAL
}

stop() {
    echo -n $"Stopping $PROG_NAME: "

    $SUPERVISOR stop $NAME

    RETVAL=$?

    if [ "$RETVAL" -eq "0" ]; then
        echo_success
    else
        echo_failure
    fi

    return $RETVAL
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    $SUPERVISOR status $NAME
    exit $?
    ;;
  restart)
    restart
    ;;
  graceful|reload)
    graceful
    ;;
  *)
    echo $"Usage: $NAME {start|stop|restart|graceful}"
    exit 1
esac

echo ""

exit 0
