# Creates zamboni settings file.
define marketplace::apps::zamboni::settings::base(
    $email_host,
    $redirect_secret_key,
    $databases_default_name,
    $databases_default_host,
    $databases_default_port,
    $databases_default_user,
    $databases_default_password,
    $databases_slave_name,
    $databases_slave_host,
    $databases_slave_port,
    $databases_slave_user,
    $databases_slave_password,
    $services_database_name,
    $services_database_user,
    $services_database_password,
    $services_database_host,
    $sphinx_host,
    $sphinx_port,
    $caches_default_location,
    $broker_host,
    $broker_port,
    $netapp_storage_root,
    $redis_backends_cache,
    $redis_backends_cache_slave,
    $redis_backends_master,
    $redis_backends_slave,
    $recaptcha_public_key,
    $recaptcha_private_key,
    $responsys_id,
    $builder_secret_key,
    $es_hosts,
    $statsd_host,
    $statsd_port,
    $statsd_prefix,
    $graphite_host,
    $graphite_port,
    $graphite_prefix,
    $email_blacklist,
    $metlog_conf_sender_host,
    $metlog_conf_sender_port,
    $google_analytics_credentials
) {

}
