#!/bin/bash

set -e
set -o nounset

CURDATE=$(date "+%Y-%m-%d")

RESET_SQL="${PROJECT_DIR}/scripts/landfill-reset.sql"

if [ -e "$RESET_SQL" ]; then
    mysql -s -u "${DB_USER}" \
        -h "${DB_HOST}" \
        "${DB_NAME}" < "$RESET_SQL"
fi

cd ${DUMP_DIR}
mysqldump -u "${DB_USER}" \
    -h "${DB_HOST}" \
    "${DB_NAME}" | gzip > "./landfill-${CURDATE}.sql.gz"

tar --transform 's,^./,amo_data/,S' \
    -czf "./landfill-files-${CURDATE}.tar.gz" -C "${FILES_ROOT}" .

find . -type f -name "landfill-*" -mtime +3 | xargs rm -f
