#!/bin/bash

set -e

for v in DUMP_DIR DB_USER MYSQL_PWD DB_HOST DB_NAME FILES_ROOT; do
    if [ -z "${!v}" ]; then
        echo "${v} must be set."
        exit 1
    fi
done

CURDATE=$(date "+%Y-%m-%d")

cd ${DUMP_DIR}
mysqldump -u "${DB_USER}" \
    -h "${DB_HOST}" \
    "${DB_NAME}" | gzip > "./landfill-${CURDATE}.sql.gz"

tar --transform 's,^./,amo_data/,' \
    czf "./landfill-files-${CURDATE}.tar.gz" -C "${FILES_ROOT}" .

find . -type f -name "landfill-*" -mtime +3 | xargs rm -f
